# Latest and greatest version :)
version: "3.7"
services:
  # Reverse proxy webserver
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      # Only nginx will have frontend accessibility
      - frontend
      - backend
    ports:
      # App
      - "8080:8080"

  app:
    image: golang:latest
    restart: always
    networks:
        - backend
    ports:
        - "3000:3000"
    volumes:
      - ./app/build.sh:/tmp/build.sh
      - ./app/conf.toml:/tmp/conf.toml
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

    command: bash -c "chmod +x /tmp/build.sh && /bin/bash /tmp/build.sh"
# Network configuration
networks:
    frontend:
    backend: